<?php
/** @var \Mugar\CustomerIdentificationDocument\Block\Adminhtml\Order\Create $block */

?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= __('Identification Document') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="order-information">
            <div class="box">
                <div class="box-content">
                    <div class="field field-cid_type admin__field required">
                        <label class="label admin__field-label" for="order-<?= $block->getSelectId() ?>">
                            <span><?= __('Type') ?></span>
                        </label>
                        <div class="control admin__field-control">
                            <select id="order-<?= $block->getSelectId() ?>"
                                    name="<?= $block->getSelectName() ?>"
                                    class="select required-entry admin__control-select validate-select" style="">
                                <?php foreach ($block->getSelectOptions() as $option) : ?>
                                    <option value="<?= $option['value'] ?>" title="<?= $option['label'] ?>">
                                        <?= $option['label'] ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field field-cid_number admin__field required">
                        <label class="label admin__field-label" for="order-<?= $block->getNumberId() ?>">
                            <span><?= __('Number') ?></span>
                        </label>
                        <div class="control admin__field-control">
                            <input id="order-<?= $block->getNumberId() ?>" name="<?= $block->getNumberName() ?>"
                                   class="input-text admin__control-text" type="text"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
